### ISSUE TITLE
Removing Cloaks cause a crash

### ISSUE THREAD

**Issue by ewsmith** [yrsegal/NaturalPledge#12]
[http://pastebin.com/fr2ZVwQD](http://pastebin.com/fr2ZVwQD)

**Comment by Alaberti** [comment]
Same problem: http://pastebin.com/raw/8fKQThev

Natural Pledge r.16
Baubles 1.3.0
Botania r1.9-337

**Comment by yrsegal** [comment]
fixed on baubles' side
