### ISSUE TITLE
Missing dependency to librarianlib

### ISSUE THREAD

**Issue by MatthiasMann** [yrsegal/NaturalPledge#15]
The mod does not list librarianlib as a required mod which leads to a NoClassDefFoundError crash instead of the more helpful forge error screen.

I'm using NaturalPledge-r1.7.jar

**Comment by Zygus42** [comment]
Is that this error which I've just started getting ?

[crash-2017-01-02_16.47.27-client.txt](https://github.com/yrsegal/NaturalPledge/files/680566/crash-2017-01-02_16.47.27-client.txt)

Strange thing is that it was working, and then I upped my RAM usage a gig, and it started crashing with this error - pretty weird.

**Comment by Zygus42** [comment]
never mind me - just realised that you've added library lib dependency that I didn't have - too many late nights i guess :)   keep up the good work.

**Comment by MatthiasMann** [comment]
That is exactly the crash I mentioned :)

**Comment by yrsegal** [comment]
This is what I get for updating when tired. Hotfix soon.

**Comment by yrsegal** [comment]
0b3f5b74d833a011b396db24ce489c974a453b07
