### ISSUE TITLE
Crash when Heimdall's bifrost power tries to place a block outside of the world

### ISSUE THREAD

**Issue by quat1024** [yrsegal/NaturalPledge#17]
There's a couple ways to trigger it while pledged to Heimdall and holding a rod of the bifrost:

* Go to y=1 and shift
* Go above y=255
* Fall below y=0

Log: http://paste.ee/p/LPnwZ (line 643)

If you are holding a rod of the bifrost are outside of the y=0-255 range **you crash immediately when you log in and have to MCEdit your position!!!!!!!**

**Comment by yrsegal** [comment]
whoops.
