### ISSUE TITLE
[Bug] Console spam

### ISSUE THREAD

**Issue by MysticAura** [yrsegal/NaturalPledge#22]
MC: 1.10.2
Forge: 2185
Mod Version: NaturalPledge-r1.10

For some reason  this mod is trying to feed JEI names one letter at a time. Which is creative, but I doubt intended. The spam disappears when this mod is removed.

[Console Spam](http://pastebin.com/772v5SJC)

[Referenced Here](https://github.com/mezz/JustEnoughItems/issues/737)

**Comment by yrsegal** [comment]
Fixed on my end. JEI updated its API, breaking my wrapper.

As for why I haven't pushed it, I wasn't on internet at the time. I'll get
the fix out soonish.
