### ISSUE TITLE
Saplings and Leaves don't have textures

### ISSUE THREAD

**Issue by followmylogic** [yrsegal/NaturalPledge#23]
All of the NP saplings I've tried have no textures as do their leaves. They grow with bone meal and the logs are properly textured.

**Comment by yrsegal** [comment]
I know what's going on, it's an error in the statemapper

**Comment by Divineaspect** [comment]
Is this going to be fixed or should we use resource loaders to work around?

**Comment by yrsegal** [comment]
Fixed for next rel
