### ISSUE TITLE
Network lag

### ISSUE THREAD

**Issue by LemADEC** [yrsegal/NaturalPledge#26]
As seen here: https://github.com/yrsegal/NaturalPledge/blob/master/src/main/java/shadowfox/botanicaladdons/common/items/travel/stones/ItemWaystone.kt#L61
Mod is sending network packets to all player every tick with all the waystone.
Consider sending those packets only every few seconds instead.

**Comment by yrsegal** [comment]
The game already sends tons of packets per tick. Why is this one changing anything?

If you can prove to me this is actually causing network lag, i'll consider it. Until then, this remains closed.

**Comment by LemADEC** [comment]
You really think I found that issue by chance?
