### ISSUE TITLE
Crash about tinker costruct

### ISSUE THREAD

**Issue by bigrice1018** [yrsegal/NaturalPledge#28]
[crash-2017-03-23_21.50.17-client.txt](https://github.com/yrsegal/NaturalPledge/files/876227/crash-2017-03-23_21.50.17-client.txt)
Using 1.10.2 Least version of both mods

**Comment by yrsegal** [comment]
Turn it off in the NP config

**Comment by bigrice1018** [comment]
There is only # Configuration file

in the config

**Comment by yrsegal** [comment]
Well it's there in mine
