### ISSUE TITLE
conflict between plustic and NaturalPledge

### ISSUE THREAD

**Issue by scalda** [yrsegal/NaturalPledge#31]
Hi i will be posting this on the PlusTic issues page aswell.

But there is an issue where your mod is trying to register manasteel to tinkers when plustic already has, please see the crash report attached.

[crash-2017-03-31_11.18.34-client.txt](https://github.com/yrsegal/NaturalPledge/files/885261/crash-2017-03-31_11.18.34-client.txt)

Regards
Scalda
(Lead dev for FoolCraft)

**Comment by Landmaster** [comment]
This is a duplicate of #27, isn't it?

**Comment by scalda** [comment]
looks like it but i am using all latest 1.10.2 versions of the mod and the required mods to load.

Forgelin-1.4.1.jar
librarianlib-1.10.1.jar
NaturalPledge-r1.11.jar

and they are what i get the conflict with, the plustic dev closed my issue and said it's been fixed?

**Comment by Landmaster** [comment]
@scalda Turn off Tinkers Construct/Botania integration for either PlusTiC or Natural Pledge in order to resolve the conflict.

**Comment by scalda** [comment]
ok thank you, i disabled plustic, as your modifiers were better lol

**Comment by Landmaster** [comment]
Just saying though, I am the dev of PlusTiC, *not* Natural Pledge (FYI @yrsegal is Natural Pledge's dev).
