### ISSUE TITLE
DON'T USE v3

### ISSUE THREAD

**Issue by ruyanve** [yrsegal/NaturalPledge#32]
1.11.2 Forge 2282

log: https://gist.github.com/ruyanve/06d43a76a495b451e17f486492c3b312

Not much more to say...
Cheers

**Comment by drakray** [comment]
very similar [crash](https://pastebin.com/P7Hcs0CE)

**Comment by yrsegal** [comment]
Don't use v3 yet, it's not yet supported

**Comment by starg09** [comment]
As a suggestion, maybe mark v3/3.1 as alpha? Just so curse doesn't offer it as an update inmediately to those using v2.

**Comment by Sunconure11** [comment]
https://pastebin.com/mHsBt2Gk

It looks like this crash happens even with the 2.0 version on curse. Not sure what is going on.

**Comment by starg09** [comment]
@Sunconure11 you're using v3.1 of LibrarianLib, make sure you're actually on v2.x before reporting :/

**Comment by Sunconure11** [comment]
God damnit, I'll see what happens if I revert.

**Comment by yrsegal** [comment]
r2.2 of natural pledge, finally, exists
