### ISSUE TITLE
item in travellers toolbelt too large to retrieve

### ISSUE THREAD

**Issue by superon** [yrsegal/NaturalPledge#37]
playing foolcraft 1.3.3, idk if that's really relevant but thought i should probably mention it, i found the config and i gather from it you will have received a crash report or similar after what just happened whilst playing on a server... i put a storage module tablet full of things in the travellers toolbelt, that's np but trying to get the tablet back from it crashes the client with the message "Internal Exception: java.lang.IllegalArgumentException
Payload may not be larger than 32767 bytes"
ummm, anyway to get the module back or is it forever stuck in there now?

**Comment by yrsegal** [comment]
I think it's fixed in the next version.

**Comment by yrsegal** [comment]
Which will be out... sometime. Idk.

**Comment by superon** [comment]
thanks, i'll wait indefinitely to retrieve them items then...  pushing for a little more info tho sorry and only if you know ofc, will the next version be included in the next release of foolcraft?
