### ISSUE TITLE
ender actuator - client crash

### ISSUE THREAD

**Issue by superon** [yrsegal/NaturalPledge#38]
placed one of these and right-clicked it to be greeted by a crash, doesn't crash in sp, just mp so far

**Comment by yrsegal** [comment]
Could you give me a log?

**Comment by superon** [comment]
i'm unable to join the server atm to recreate this for a log due to a ticking player problem

**Comment by superon** [comment]
weeelll i finally managed to get back onto the server to get the crashlog for ye...   seems somewhere along the line (server was reinstalled updated downgraded and fondled with) this issue has been fixed as i'm not getting a crash anymore :)  i'll reopen if i should discover why (if still relevant) or it happens again. cheersy
