### ISSUE TITLE
tree leaves and saplings appear untextured

### ISSUE THREAD

**Issue by superon** [yrsegal/NaturalPledge#39]
tree leaves and saplings appear untextured, they grow fine and don't cause a crash but i thought i'd log it here so you know:/  
running these:
Baubles-1.10.2-1.3.9
Botania r1.9-341
Forgelin-1.4.1
librarianlib-1.10.1
NaturalPledge-r1.9.1

**Comment by yrsegal** [comment]
known, fixed for next version
