### ISSUE TITLE
mysterious error involving blockstate initialization

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/NaturalPledge#4]
https://gist.github.com/SkySom/213322fb180a1f086400f92c696d1c42

**Comment by williewillus** [comment]
If you're on the latest forge build from today it's probably this that caused it (maybe?)
https://github.com/MinecraftForge/MinecraftForge/commit/ab64d1a1665e93b3d1fa46065119356eabe7efd3

**Comment by 0Navis0** [comment]
Oh yeah it's the issue I reported.

**Comment by williewillus** [comment]
You need to register your blocks after setting default state

**Comment by williewillus** [comment]
@yrsegal

**Comment by yrsegal** [comment]
oh, I see. Thanks for the heads up
