### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by CluelessPhil** [yrsegal/NaturalPledge#40]
I am testing a custom pack and it had a crash. No other mods have crashed and Natural Pledge doesnt seem like it'd conflict with the mods I've installed. Here is the link to the crash log, https://pastebin.com/nwdwq2QR 

This is the issue it has generated: Caused by: java.lang.NoClassDefFoundError: shadowfox/botanicaladdons/common/core/tab/ModTab

**Comment by yrsegal** [comment]
Don't use liblib v3

**Comment by CluelessPhil** [comment]
Thanks

**Comment by CluelessPhil** [comment]
Should i use v2 or a different version of v3?

**Comment by yrsegal** [comment]
v2, until the next NP release
