### ISSUE TITLE
crashes with latest librarianlib

### ISSUE THREAD

**Issue by lag42** [yrsegal/NaturalPledge#41]
crash log here:
https://pastebin.com/KvQNEkHZ

**Comment by lag42** [comment]
Nevermind, looked at commits and saw something that should fix my issue

**Comment by drakray** [comment]
Care to explain please? I got the same crash :/
EDIT: using Forge 2366

**Comment by brisingraerowing** [comment]
I get this crash as well.

@yrsegal

**Comment by lag42** [comment]
refer to that issue now, i thought i should close it just because i was convinced it was fixed in dev
