### ISSUE TITLE
crashes upon startup

### ISSUE THREAD

**Issue by lag42** [yrsegal/NaturalPledge#42]
https://github.com/yrsegal/NaturalPledge/issues/41 for some reason i thought i should close it because it looks like its likely fixed in dev but then people reported having the same issue and that reminded me this is still valid as long as this happens in the latest release. downgrading versions of librarianlib doesn't help a bit, originally thought this was liblib or using a hook that was removed, crash log here:
https://pastebin.com/KvQNEkHZ

**Comment by Sunconure11** [comment]
I think @yrsegal needs to upload a specific version of natural pledge to curse at this point, as I managed to get both working... but only with a test build he created on a discord channel.

**Comment by drakray** [comment]
NP 2.3 on Curse seems to fix this

**Comment by lag42** [comment]
Well as long as it's on curse it's a valid fix and I read the changelog and it specifically addresses this issue
