### ISSUE TITLE
Saplings falling from the sky no trees

### ISSUE THREAD

**Issue by Hazmatik** [yrsegal/NaturalPledge#6]
I used birch saplings around pure daisy to make iridescent saplings after i harvested them birch saplings started falling from the sky all around and there were no trees nearby. It was way more saplings than the 8 I put around the pure daisy too.

Edit: Circuitree saplings then started falling/being placed in the sky after i planted one of them.

**Comment by gchpaco** [comment]
I have this too, although it was with calico saplings.  There is something seriously goofy about the way the passive buff from Idunn's priest emblem is implemented, it seems to cause saplings to reproduce themselves in really weird locations, like midair or underwater or in the middle of my farm.

**Comment by yrsegal** [comment]
please provide exact steps to reproduce, including the list of mods.

**Comment by gchpaco** [comment]
Reproduced with All The Mods v1.17.  Wear Idunn's amulet, have mana in inventory, plant birch sapling, walk around a bit.  See birches planted in weird random locations in the sky, which despawn.

**Comment by yrsegal** [comment]
That's strange, since all idunn's emblem does is bonemeal...

**Comment by yrsegal** [comment]
Can you reproduce it with Natural Pledge (and Botania/baubles) alone?

**Comment by gchpaco** [comment]
Yup.  Key is to move around and especially change y levels.  I see bonemeal particles in mid air, and occasionally they seem to summon a cloned sapling from nowhere, which periodically receives block updates and figures out it shouldn't be there.

![2016-08-28_13 58 26](https://cloud.githubusercontent.com/assets/17789/18036717/9f804bb8-6d27-11e6-928d-2c1a9e9bf83e.png)
This shows both problems.  Equipment is a mana tablet with mana in it, and Idunn's amulet.

**Comment by gchpaco** [comment]
Suppose I should mention.  Modpack consists of Baubles 1.2.1.0, Botania Unofficial r1.8-320 (newest), Natural Pledge r1.5.
