### ISSUE TITLE
Botania internal refactor of proxy breaks NP

### ISSUE THREAD

**Issue by williewillus** [yrsegal/NaturalPledge#7]
NP seems to be using Botania's internal proxy.

I refactored it this latest build to get rid of the silly CommonProxy pattern, which changed the class of the field NP compiles against from `CommonProxy` to `IProxy`

Just a heads up as I just tried to start a modpack up and NP would crash due to that field shifting class.

Ideally tell me what you need from there and it should get lifted into the API..

**Comment by yrsegal** [comment]
What you refactored just required me to change stuff to work with the new syntax. Not a problem.
