### ISSUE TITLE
Enchantment description support

### ISSUE THREAD

**Issue by Darkhax** [yrsegal/NaturalPledge#9]
A few of my mods (Wawla, Enchanting Plus, along with a new WIP) have features which provide players with descriptions of enchantments. These features use localization keys to get the description for an enchantment. The format is very basic, `enchantment.MODNAME.ENCHNAME.desc` where `MODNAME` and `ENCHNAME` are both taken from the string based ID for the enchantment. I would really appreciate it if support for this would be added to the enchantments in Natural Selection 2. The following is a list of keys for Natural Pledge enchantments. 

```
enchantment.botanicaladdons.heavy.desc
enchantment.botanicaladdons.light.desc
```

**Comment by yrsegal** [comment]
Sure, I'll do it for next release.
